[package]
authors = ["Matthias <matthias.seitz@tum.de>"]
name = "plexapi"
version = "0.1.0"

[dependencies]
futures = "0.1.17"
reqwest = "0.8.1"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"
tokio = "0.0.0"
